### ISSUE TITLE
Prop rotation changes when releasing prop

### ISSUE THREAD

**Issue by friesofdoom** [ThatFatKidsMom/Grabbable-Prop#1]
When I let go of the prop, the rotation is often nowhere near where it was before I dropped it. Is this the case for everyone or is it something I broke in my integration?

**Comment by ThatFatKidsMom** [comment]
Its the case for everyone. This prefab was only meant to manipulate position of spawned objects so it has nothing that would allow for rotation in its current state. The avatar-prop repo is what this evolved into so that it could have that functionality.

**Comment by friesofdoom** [comment]
whoops, wrong repo! this was an issue for the other repo
